name: Java maven cicd

on:
  workflow_dispatch:
  push:
    branches: [ master, samanthchakravarthy-test-commit ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up JDK 11
      uses: actions/setup-java@v2
      with:
        java-version: '11'
        distribution: 'adopt'

    - name: Build project with Maven
      run: | 
        mvn -B package --file pom.xml
        mkdir staging && cp target/*.jar staging
        
    - name: Persist workflow data as artifacts
      uses: actions/upload-artifact@v2
      with:
        name: gitHub-actions-artifact
        path: staging
        
  deploy_to_test-env:
    runs-on: ubuntu-latest
    needs: build
    #if: github.event_name != 'pull_request'
    environment: test-environment
    steps:
    - name: Download a Deployment Zip
      uses: actions/download-artifact@v2
      with:
        name: gitHub-actions-artifact_zip
   
